apiVersion: v1
kind: Service
metadata:
   name: fe-identifier-service
   namespace: identifier-app
spec:
   selector:
      app: fe-gan-identifier
   ports:
      - protocol: TCP
        port: 80
        targetPort: 80
   type: NodePort
